### ISSUE TITLE
'maven install' error

### ISSUE THREAD

**Issue by tungchiminh** [jMetal/jMetal#339]
When I use maven3 to  install jMetal, the printed information is as follows:

```
mvn install                   
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 5 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 5 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] org.uma.jmetal:jmetal                                              [pom]
[INFO] org.uma.jmetal:jmetal-core                                         [jar]
[INFO] org.uma.jmetal:jmetal-problem                                      [jar]
[INFO] org.uma.jmetal:jmetal-algorithm                                    [jar]
[INFO] org.uma.jmetal:jmetal-exec                                         [jar]
[INFO] 
[INFO] -----------------------< org.uma.jmetal:jmetal >------------------------
[INFO] Building org.uma.jmetal:jmetal 5.8-SNAPSHOT                        [1/5]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.7.201606060606:prepare-agent (default) @ jmetal ---
[INFO] argLine set to -javaagent:/home/turner/.m2/repository/org/jacoco/org.jacoco.agent/0.7.7.201606060606/org.jacoco.agent-0.7.7.201606060606-runtime.jar=destfile=/home/turner/GitHub/jMetal/target/jacoco.exec
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.7.201606060606:report (report) @ jmetal ---
[INFO] Skipping JaCoCo execution due to missing execution data file.
[INFO] 
[INFO] --- maven-source-plugin:2.2.1:jar-no-fork (attach-sources) @ jmetal ---
[INFO] 
[INFO] --- maven-javadoc-plugin:3.0.1:jar (attach-javadocs) @ jmetal ---
[INFO] Not executing Javadoc as the project is not a Java classpath-capable package
[INFO] 
[INFO] --- maven-site-plugin:3.7.1:attach-descriptor (attach-descriptor) @ jmetal ---
[INFO] No site descriptor found: nothing to attach.
[INFO] 
[INFO] --- maven-failsafe-plugin:2.18.1:integration-test (integration-test) @ jmetal ---
[INFO] No tests to run.
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] 
[INFO] --- maven-gpg-plugin:1.5:sign (sign-artifacts) @ jmetal ---
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for org.uma.jmetal:jmetal 5.8-SNAPSHOT:
[INFO] 
[INFO] org.uma.jmetal:jmetal .............................. FAILURE [  1.524 s]
[INFO] org.uma.jmetal:jmetal-core ......................... SKIPPED
[INFO] org.uma.jmetal:jmetal-problem ...................... SKIPPED
[INFO] org.uma.jmetal:jmetal-algorithm .................... SKIPPED
[INFO] org.uma.jmetal:jmetal-exec ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.061 s
[INFO] Finished at: 2019-03-09T15:00:43+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign (sign-artifacts) on project jmetal: Exit code: 2 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

The main reason may be that maven3.x performs maven-ant-plugin differently than maven2.x. When pluginManagement is introduced, it works (For all pom.xml files in jMetal repository).

```
<build>
   <pluginManagement>
   <plugins>
      <plugin></plugin>

      ... ...

       <plugin></plugin>
    </plugins>
</pluginManagement>
</build>
```

**Comment by matthieu-vergne** [comment]
Your logs show you were not able to sign the artifacts to install:
```
[INFO] --- maven-gpg-plugin:1.5:sign (sign-artifacts) @ jmetal ---
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign (sign-artifacts) on project jmetal: Exit code: 2 -> [Help 1]
```

In my case (Maven 3.3.9), it asks for my password in order to sign the artifacts, and then continue without any issue. You can run `mvn -e install` to have more details and investigate from there, but it seems to me the issue is not from our side.

**Comment by matthieu-vergne** [comment]
@tungchiminh
Were you able to fix it?

**Comment by tungchiminh** [comment]
@matthieu-vergne 
Well, I'm a heavy user of the jMetal platform. I fixed the problem with the method I said above.

I cloned jMetal from the repository to local again just now, and used the "`mvn -e install`"  (Maven 3.6.0) command to run directly, but it still reported the error I said before. However,  I added `<pluginManagement>` after `<build>`  to all pom.xml files, I can run successfully.

**Comment by matthieu-vergne** [comment]
I have to insist: no you did not solve the problem (actually there is no problem, it is a feature), you replaced it by another one. I tried adding the tag `<pluginManagement>`, and indeed it goes until the end (I had to try on a fresh install with non GPG key). But it does so because the signing step `maven-gpg-plugin:1.5:sign (sign-artifacts)` just completely disappears. Basically, it is equivalent to remove the signing plugin from the POM:
```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-gpg-plugin</artifactId>
	<version>1.5</version>
	<executions>
		<execution>
			<id>sign-artifacts</id>
			<phase>verify</phase>
			<goals>
				<goal>sign</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```
That is clearly not a solution. It is there because the JARs should be signed in order to be released on external repositories like Maven Central/Nexus Sonatype. If you add `<pluginManagement>`, the signing just goes away and the JARs remain unsigned. It looks like it simply corrupts the POM enough to not see the signing plugin anymore. THAT is a problem.

As I mentioned before, the point is that you have nothing to sign your JARs with, like a GPG key. This is why you cannot make it work and why it works on my computer (which does have GPG keys). What you want is to ignore the signing step for you to install the JARs locally. To do so, you need to ask Maven to skip the signing step with `mvn install -Dgpg.skip`. The step will still be displayed, but it will remain empty.

These are the two actual solutions:
- sign your JARs, which is easy if you have a GPG agent installed but has not much value if you only play with jMetal locally
- skip the signing step with `-Dgpg.skip`, probably the most relevant solution in your case

**Comment by tungchiminh** [comment]
@matthieu-vergne 
Thank you very much for your clarification. Yes, you are absolutely right. I signed my JARs with a GPG key, and my problem is solved. a-ha~. I hope this 'issue' will not confuse others, thanks again!

**Comment by matthieu-vergne** [comment]
You're welcome. Please close this issue, sine I don't have enough rights on the repo to do it myself.
